Add Annotations to Charm Configuration
canonical/k8s-operator pull request #154
Opened 2024-10-20 22:46 UTC by mateoflorido

## Overview
Add a charm configuration option to enable the fine grained configuration of clusters using annotations.
## Rationale
The `k8s` snap allows the use of annotations as a mechanism to configure features built into the snap. For example, to configure VLAN BPF bypass in Cilium (as requested in #112), we can use the annotation `k8sd/v1alpha1/cilium/vlan-bpf-bypass` which passes the VLAN IDs to Cilium's configuration.
## Related Issues
closes #112

2024-10-21 08:00 UTC, bschimke95 approved these changes
LGTM! Great work @mateoflorido

2024-10-21 14:23 UTC, addyess requested changes
I think the impl is right -- just have curiosity about what is being annotated and if the control-plane needs it too

2024-10-21 14:23 UTC, addyess commented on charms/worker/k8s/charmcraft.yaml
> +          e.g.: {"key1": "value1", "key2": "value2"}
are the annotations ever `key=value` pairs where key and value are non-strings?  
do the values for `key` or `value` ever contain the `=` character?  

If the answer to both of these is no, may i recommend:

```suggestion
      default: ""
      description: |
        Annotations is a space separated list of (key/value) pairs)  that can be
        used to add arbitrary metadata configuration to the Canonical
        Kubernetes cluster. For more information, see the upstream Canonical
        Kubernetes documentation about annotations:

        https://documentation.ubuntu.com/canonical-kubernetes/latest/snap/reference/annotations/

        The value for this config must be a JSON object, like this:
          e.g.: key1=value1 key2=value2
```

2024-10-21 14:23 UTC, addyess commented on charms/worker/k8s/charmcraft.yaml
> +          e.g.: {"key1": "value1", "key2": "value2"}
Also, can you say what resources we're specifically annotating?  Are they only the worker nodes?  This PR only has changed the k8s-worker charms' charmcraft.yaml?

2024-10-21 15:20 UTC, addyess commented on charms/worker/k8s/charmcraft.yaml
> +          e.g.: {"key1": "value1", "key2": "value2"}
OH OH OH... these are microcluster annotations.  I understand now that these are shared across the whole cluster using microcluster

2024-10-21 21:53 UTC, addyess commented on charms/worker/k8s/src/charm.py
> +    def _update_annotations(self):
does this need a catch for the failure condition?

```suggestion
    @status.error(...)
    def _update_annotations(self):
```

2024-10-22 14:18 UTC, addyess approved these changes
🚀 Lets go!

2024-10-22 19:02 UTC, merged