Make the jira_sync_config more KU friendly
canonical/k8s-operator pull request #87
Opened 2024-04-26 21:41 UTC by addyess

Fixes from comments:
*  https://github.com/canonical/k8s-operator/pull/84/files#diff-eee108ea49e324e51ab610c63c844d18b5b59c80bf21fd9a5b86dbecd8ad1983R12-R14

2024-04-26 21:41 UTC, addyess commented
@beliaev-maksim take a look please

2024-04-27 07:35 UTC, beliaev-maksim requested changes
Generally, LGTM

2024-04-27 07:35 UTC, beliaev-maksim commented on .github/.jira_sync_config.yaml
> +  labels: []
```suggestion
#  labels: []
```

2024-04-27 07:35 UTC, beliaev-maksim commented on .github/.jira_sync_config.yaml
> +    - K8s charm
Please ensure that this component is added in Jira (case sensitive)

You can ping me in MM

2024-04-27 13:51 UTC, beliaev-maksim commented on .github/.jira_sync_config.yaml
> +    - K8s charm
done

2024-04-29 08:26 UTC, louiseschmidtgen approved these changes
Thank you!

2024-04-29 12:50 UTC, merged